### ISSUE TITLE
SWIG bindings?

### ISSUE THREAD

**Issue by Daniel15** [graphql/libgraphqlparser#11]
The readme for libgraphqlparser includes this snippet:

>  you can use it as the basis for an extension module for your favorite programming language instead of writing your own parser from scratch.

[SWIG](http://www.swig.org/) may help with this use case. It's a tool that generates glue code to call C++ APIs from other languages. It [supports lots of different languages](http://www.swig.org/compare.html), including C#, Java, Python, Go, PHP, and Ruby. I've used it before to call a C++ API from Java and it worked pretty well for that use case.

It would be cool to include 'official' SWIG bindings to more easily allow this library to be used from other languages.

**Comment by swolchok** [comment]
I tried to write SWIG bindings for the Python example before I settled on the C API, and I concluded that good SWIG bindings for the C++ API would require manual work for each bound-to language anyway, and that this work would best be kept outside the scope of this project. (For example, the Python bindings produced by default were either crashy, required fancy SWIG work to accommodate unique_ptr nicely, and/or didn't really do what one would want in the context of an AST; I forget the exact details. I would have had to put lots of SWIG-Python code in the SWIG file.) I picked the C API because most modern programming languages have good C FFI support (e.g., Python, Ruby, Go, Haskell, OCaml, Lua, .NET, Java, etc.), and you can typically call C functions and "muddle through" without too much work, even if you have to use a libffi-based solution like Python's ctypes or Ruby's Fiddle to do it.

That said, I do agree that rich, idiomatic bindings like SWIG helps you produce are better and would love to see them for as many programming languages as possible!
