### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by kurayama** [graphql/libgraphqlparser#7]
The README should clarify about the thread safety of the library so it's clearer if/how to use on multithreaded environments.

**Comment by swolchok** [comment]
This is a great point, thanks for raising it! I don't think I've correctly set up the thread safety (re-entrant parser) options for bison and flex yet, and we'll want to fix that to enable the multithreaded server use case. I'd prefer to just fix the problem rather than document it in the README, then fix it, then change the documentation, so I'll look into how much work it will take today.
